export const apiArr = [
  '회원가입',
  '로그인',
  '로그아웃',
  'Main MAP',
  'festival list',
  'festival detail',
  'artist list',
  'artist detail',
  'country category',
  'my fessport',
  'userinfo edit',
  'wish list',
  'my post',
  'like festival',
  'like artist',
  'dislike festival',
  'dislike artist',
  'visited festival',
  'visited cancel',
  'insert data',
];
